language: bash
sudo: required
branches:
  only:
  - main
services:
- docker
before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t coolsandythombare/microservice-python:$TRAVIS_BUILD_NUMBER .
  - docker push coolsandythombare/microservice-python
script:
- bash scripts/updatekube.sh
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: main