apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-python
  namespace: default
  labels:
    app: microservice-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-python
  template:
    metadata:
      labels:
        app: microservice-python
    spec:
      containers:
        - name: microservice-python
          image: coolsandythombare/microservice-python:VERSION
          ports:
            - containerPort: 80
              name: http