apiVersion: v1
kind: Service
metadata:
  name: microservice-python
  namespace: ns2
  labels:
    app: microservice-python
spec:
  selector:
    app: microservice-python
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      name: http
